debug: false

logging:
  level:
    com.backend.mes: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  datasource:
    url: jdbc:mysql://58.79.16.12:3306/athlete
    username: athlete
    password: athlete
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL57Dialect
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
server:
  port: 9081
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: eyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJ1c2VyIn0I2qOfhAZMGSH1pCecUH5sV2Lg2pSWNQMPzXsMcne6NJ1SlkBoirhGAmKfTYNcRyhu6nQtRzgAd6VXyttoX9A
  expiration_time: 18000000

file:
  upload-dir: ${user.home}/study-project/image

front_end_url: "http://passionathlete.com"