name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker daemon for insecure registry
        run: |
          echo '{"insecure-registries":["58.79.16.12:5000"]}' | sudo tee /etc/docker/daemon.json > /dev/null
          sudo systemctl restart docker

      - name: Log in to Docker registry using HTTP
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login http://58.79.16.12:5000 --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Debug Environment Variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}"
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}"
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}"

      - name: Build Docker image
        run: |
          docker build --build-arg DB_URL=${{ secrets.DB_URL }} \
                       --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
                       --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                       --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
                       -t 58.79.16.12:5000/athlete_user:${{ github.sha }} .

      - name: Push Docker image to registry
        run: |
          docker push 58.79.16.12:5000/athlete_user:${{ github.sha }}

      - name: Add additional tag and push
        run: |
          docker tag 58.79.16.12:5000/athlete_user:${{ github.sha }} 58.79.16.12:5000/athlete_user:latest
          docker push 58.79.16.12:5000/athlete_user:latest
